


From openjdk:17-jdk-slim

LABEL "org.opencontainers.image.authers"="nextalien.com"

COPY target/accounts-0.0.1-SNAPSHOT.jar accounts-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","accounts-0.0.1-SNAPSHOT.jar"]

